### PR TITLE
add dead containers to containers.dead

### LINKED ISSUE #60: Support for removing Dead containers?
Thank you for docker-gc, it is working nicely for us.

What I did notice is that it doesn't currently remove `Dead` containers (or it tries and is unsuccessful).

It looks like docker-gc wants to keep them:

```
$ docker ps -a | grep Dead
45c3be6ad58e        myimage              "myproc"   4 days ago          Dead
66feab2765bd        myimage              "myproc"   4 days ago          Dead
2a45be87379e        myimage              "myproc"   4 days ago          Dead
b8d073da4fac        myimage              "myproc"   4 days ago          Dead
c0dba5cc5f20        myimage              "myproc"   4 days ago          Dead

$ grep 45c3b /var/lib/docker-gc/*
/var/lib/docker-gc/containers.all:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/containers.exited:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/containers.keep:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/containers.reap.tmp:45c3be6ad58e726f792bd740376551cae7072815e0ae5cfd80a663d7809dc173
/var/lib/docker-gc/exclude_container_ids:45c3be6ad58e

$ grep 66fea /var/lib/docker-gc/*
/var/lib/docker-gc/containers.all:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/containers.exited:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/containers.keep:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/containers.reap.tmp:66feab2765bd8527628436ae8b81980348de74855b0289407be3d4e4fec58bee
/var/lib/docker-gc/exclude_container_ids:66feab2765bd
```

Although not necessarily common, it would be good to cover these or at least output them to a `.dead` file which can be monitored and addressed a person or another tool.

### PR DESCRIPTION
**Pull request by konstruktoid**
Since the dead state is kinda odd, don't remove the container and instead append `containers.dead` for manual cleaning.

Closes #60 

Signed-off-by: Thomas Sjögren konstruktoid@users.noreply.github.com

### CODE REVIEW

**Comment by mattnworb** [comment]
1. If the dead container was previously being removed, I don't think this change will result in any change as it is just appended to `containers.dead`, won't it?

2. Seems like the file will be continually appended to on each run of `docker-gc` and never have it's contents cleaned up, is that of any concern to you?

**Comment by konstruktoid** [comment]
Hi, sorry for the late reply.

As of https://github.com/konstruktoid/docker-gc/commit/732a3fe314facd88011a842dcedf4b1458d5d44b: 
1. That's correct, there's no changes done except the containers getting appended to `containers.dead`.
2. Yes and no. If you're constantly having dead containers show up in the file, you might have disk usage issues in the long run, but with that said, if you're constantly having dead containers something broken.

Will submit updated PR.

**Comment by konstruktoid** [comment]
With https://github.com/konstruktoid/docker-gc/commit/411009772c74dae41f80cea5a191193e0fedd201 logging is added and the `containers.dead` file is cleaned on each run.

**Comment by harmw** [comment]
while implementing a similar fix, I noticed the `inspect` is now allowed:
```
$ docker inspect -f "{{.State.Dead}}" big_tesla
Error: No such image or container: big_tesla
```
Even though that container does exists, in state _Dead_.
```
34bba39b8f1a        registry:2.0.1                            "registry cmd/registr"   4 days ago          Dead                                                                                                             big_tesla
```

**Comment by konstruktoid** [comment]
Dead.

**Pull request closed without merging**
