### PR TITLE
Added support for missing -s option of pidof on MacOS

### PR DESCRIPTION
**Pull request by Niyakiy**
As we have docker beta available natively for MacOS it would be nice to be able to run GC collector directly on MacOS. This pull request fixes missing `-s` option to pidof on MacOS.

### CODE REVIEW

**Comment by mattnworb** [comment]
my understanding is that `pidof` doesn't exist in OS X, at least unless you install an extra package or tool from somewhere. @Niyakiy did you install something that adds pidof on OS X?

**Comment by Niyakiy** [comment]
@mattnworb sure - I've used brew to install pidof as it isn't standard part of MacOS. 
Yes native only tools should be used `ps ax | grep 'docker-gc' | awk '{print $1}' | head -1` to search for a PID. I'm going to update pull-request.

**Comment by Niyakiy** [comment]
@mattnworb  sure - I've used brew to install pidof tool om MacOS.

**Comment by caipre** [comment]
Closing; superceded by https://github.com/spotify/docker-gc/pull/86

**Pull request closed without merging**
