### PR TITLE
Add DRY_RUN option

### PR DESCRIPTION
**Pull request by zerthimon**
This patch provides DRY_RUN option to test the settings before the run.
ex:
```
DRY_RUN=1
```

### CODE REVIEW

**Comment by mbruggmann** [comment]
Could you squash your commits? :+1: for the functionality

**Comment by zerthimon** [comment]
https://github.com/zerthimon/docker-gc/commit/a3b2d2aa111ba4ca99b6b8e27b6a389bb610f67d
Hm, this commit is the squash, I thought.

**Comment by zerthimon** [comment]
@mbruggmann anything else I can do to make this PR merged ?

**Comment by emmetog** [comment]
@zerthimon the PR now has 4 commits in it, when you've squashed all the commits into one there will only be 1 single commit in this PR.

Here's a guide that might help you:
https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

**Comment by zerthimon** [comment]
@emmetog @mbruggmann 

PR is fixed
(the wrong step from my side was to merge after rebase, had to use forced commit)

**Comment by mattnworb** [comment]
@zerthimon thanks!

**Comment by DeviaVir** [comment]
@mattnworb @mbruggmann the docker build for this change failed, any chance you could kick it?
https://hub.docker.com/r/spotify/docker-gc/builds/bhxisqpuqaotobglstrba58/

**Comment by mattnworb** [comment]
@DeviaVir thanks for the heads up. I triggered https://hub.docker.com/r/spotify/docker-gc/builds/buw596blrgvwjvp4g72imvr/

**Pull request merged**
