### PR TITLE
Docker version 1.8.2

### PR DESCRIPTION
**Pull request by konstruktoid**
Bump Docker version to latest stable.

```sh
$ docker run -ti --rm -v /var/run/docker.sock:/var/run/docker.sock -v /etc:/etc spotify/docker-gc sh
/ # docker version
Client:
 Version:      1.8.2
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0a8c2e3
 Built:        Thu Sep 10 19:10:10 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.0-dev
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   02ae137
 Built:        Fri Sep 25 17:37:00 UTC 2015
 OS/Arch:      linux/amd64
 Experimental: true
/ #
```

Signed-off-by: Thomas Sjögren <konstruktoid@users.noreply.github.com>

### CODE REVIEW

**Comment by dangra** [comment]
For people not using latest stable on their servers, it means docker image won't work anymore. Is there any known docker-gc bug fixed by upgrading docker on the client side?

**Comment by konstruktoid** [comment]
Sorry for the late reply @dangra, and yes you are correct, this will break backwards compatibility.
And while there isn't a known docker-gc bug 1.6.2 was released around six months ago, so this PR is more about keeping system and application up-to-date.

**Comment by dangra** [comment]
hi @konstruktoid, I understand your motivation and I don't mind maintaining an older version of docker-gc for my systems, but to be clear it is not 1.6.2 what worries me but 1.7.1 that was released 3 months ago. Worth saying 1.7.1 is coreos stable default too.

**Comment by konstruktoid** [comment]
So 1.7.1 could be some sort of middle-ground?

I tried to get current docker versions in various distros, RHEL missing since I dont have any account ...
[Alpine](https://pkgs.alpinelinux.org/package/community/x86_64/docker) - 1.8.2-r3
[Fedora, OpenSuSE](http://fr2.rpmfind.net/linux/rpm2html/search.php?query=docker&submit=Search+...) - 1.8.2
[CoreOS](https://coreos.com/releases/) - 1.7.1
[Debian Jessie](https://packages.debian.org/jessie-backports/docker.io) - 1.6.2
[Ubuntu trusty 14.04LTS](http://packages.ubuntu.com/search?suite=all&section=all&arch=any&keywords=docker.io&searchon=names) - 0.9.1(!?)

**Comment by dangra** [comment]
1.7.1 sounds reasonable to me but I'm afraid I am not involved with Spotify nor I am a maintainer of this project. IMHO at the end the minimum version will depend on what Spotify uses internally.

**Comment by mattnworb** [comment]
Thanks @konstruktoid for the contribution!

As @dangra guessed, we are using 1.6 internally at the moment so I am loathe to merge this at this time.

However since building the image for a different Docker version only requires editing this one line, I'll make sure to document how it can be build for other Docker versions in the README.

**Comment by konstruktoid** [comment]
Thanks @mattnworb for letting me know. Closing.

**Pull request closed without merging**
